### ISSUE TITLE
Issues with fetch_ucsc.py

### ISSUE THREAD

**Issue by harshameghadri** [YangLab/CIRCexplorer2#17]
I have been trying to use the inbuilt python script to get the reference genomes. This is the error I constantly get.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/fetch_ucsc.py", line 9, in <module>
    load_entry_point('CIRCexplorer2==2.3.2', 'console_scripts', 'fetch_ucsc.py')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/circ2/fetch_ucsc.py", line 89, in main
    fetch_file(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/circ2/fetch_ucsc.py", line 32, in fetch_file
    outf.write(gzip.open('refFlat.txt.gz', 'rb').read())
TypeError: write() argument must be str, not bytes

_Is there any way to get around this error?_

_I have downloaded the hg38 assembly; could I use this alternatively to create GTF flies?. If so How?_

**Comment by kepbod** [comment]
Bug has been fixed. Please try the latest version.
