### ISSUE TITLE
AS detection error in CIRCExxplorer2 devono?

### ISSUE THREAD

**Issue by tw7649116** [YangLab/CIRCexplorer2#24]
Dear CIRCexplorer2 team,

First thanks for provide such a good tool for circRNA study. Now I am trying to using CIRC2 to do the circRNA alternative splicing detecting. When I follow the manual in the "denovo" step, I got a error below:

Traceback (most recent call last):
  File "/home/tongwei/miniconda3/bin/CIRCexplorer2", line 11, in <module>  sys.exit(main())
  File "python3.6/site-packages/circ2/command_parse.py", line 59, in main command=command_log, name='denovo')
  File "python3.6/site-packages/circ2/helper.py", line 38, in wrapper  fn(*args)
  File "python3.6/site-packages/circ2/denovo.py", line 70, in denovo  annotate_fusion(ref_path, options['--bed'], denovo_flag=1)
  File "python3.6/site-packages/circ2/annotate.py", line 47, in annotate_fusion genes, novel_genes, gene_info, chrom_info = parse_ref(ref_f, 1)
  File "python3.6/site-packages/circ2/parser.py", line 75, in parse_ref starts = [int(x) for x in line.split()[9].rstrip(',').split(',')]
  File "python3.6/site-packages/circ2/parser.py", line 75, in <listcomp> starts = [int(x) for x in line.split()[9].rstrip(',').split(',')]
ValueError: invalid literal for int() with base 10: '"XXXXXXXXXX(gene_id)"'

The command is: CIRCexplorer2 denovo -r gtf -g ref.fa --as=AS --abs=ABS -b STAR_fusion_junction.bed --rpkm --no-fix > CIRCexplorer2_denovo.log

The GTF file is like this:
xpSc0053480     XX     exon    128880  128963  .       -       .        gene_id "CSA022660" transcript_id "CSA022660.1"  exon_number "1"  exon_id "CSA022660.1.1"
 xpSc0053480     XX     exon    129316  129384  .       -       .        gene_id "CSA022660" transcript_id "CSA022660.1"  exon_number "2"  exon_id "CSA022660.1.2"
xpSc0053480     XX     exon    129475  129540  .       -       .        gene_id "CSA022660" transcript_id "CSA022660.1"  exon_number "3"  exon_id "CSA022660.1.3"
xpSc0053480     XX     exon    129677  129847  .       -       .        gene_id "CSA022660" transcript_id "CSA022660.1"  exon_number "4"  exon_id "CSA022660.1.4"
xpSc0053480     XX     exon    129929  130278  .       -       .        gene_id "CSA022660" transcript_id "CSA022660.1"  exon_number "5"  exon_id "CSA022660.1.5"
xpSc0053480     XX     exon    131060  131340  .       -       .        gene_id "CSA022660" transcript_id "CSA022660.1"  exon_number "6"  exon_id "CSA022660.1.6"

What may caused this error? 
Thanks for the help.

**Comment by kepbod** [comment]
The `-r` parameter only accepts genepred format ([see here](https://circexplorer2.readthedocs.io/en/latest/modules/denovo/)). The format of genepred file is listed [here](https://circexplorer2.readthedocs.io/en/latest/modules/annotate/).

**Comment by tw7649116** [comment]
> The `-r` parameter only accepts genepred format ([see here](https://circexplorer2.readthedocs.io/en/latest/modules/denovo/)). The format of genepred file is listed [here](https://circexplorer2.readthedocs.io/en/latest/modules/annotate/).

Thanks. I'll try.
