### ISSUE TITLE
error about CIRCexplorer2 annotate

### ISSUE THREAD

**Issue by smm19900210** [YangLab/CIRCexplorer2#3]
that is my command: CIRCexplorer2 annotate -r Soly_refFlat.txt -g Solanum_lycopersicum.SL2.40.genome.fa circ_out/ > CIRCexplorer
 but i met a error:
Traceback (most recent call last):
  File "/home/songmm/songmm/CIRCexplorer2-2.1.0/CIRCexplorer2/bin/CIRCexplorer2", line 9, in <module>
    load_entry_point('CIRCexplorer2==2.1.0', 'console_scripts', 'CIRCexplorer2')()
  File "/home/songmm/songmm/CIRCexplorer2-2.1.0/CIRCexplorer2/lib/python2.7/site-packages/CIRCexplorer2-2.1.0-py2.7.egg/circ2/command_parse.py", line 51, in main
    command=command_log, name='annotate')
  File "/home/songmm/songmm/CIRCexplorer2-2.1.0/CIRCexplorer2/lib/python2.7/site-packages/CIRCexplorer2-2.1.0-py2.7.egg/circ2/helper.py", line 35, in wrapper
    fn(*args)
  File "/home/songmm/songmm/CIRCexplorer2-2.1.0/CIRCexplorer2/lib/python2.7/site-packages/CIRCexplorer2-2.1.0-py2.7.egg/circ2/annotate.py", line 31, in annotate
    annotate_fusion(options['--ref'], annotate_dir)
  File "/home/songmm/songmm/CIRCexplorer2-2.1.0/CIRCexplorer2/lib/python2.7/site-packages/CIRCexplorer2-2.1.0-py2.7.egg/circ2/annotate.py", line 43, in annotate_fusion
    genes, novel_genes, gene_info, chrom_info = parse_ref(ref_f, 1)
  File "/home/songmm/songmm/CIRCexplorer2-2.1.0/CIRCexplorer2/lib/python2.7/site-packages/CIRCexplorer2-2.1.0-py2.7.egg/circ2/parser.py", line 74, in parse_ref
    ends = [int(x) for x in line.split()[10].split(',')[:-1]]
IndexError: list index out of range

**Comment by kepbod** [comment]
Please make sure your Soly_refFlat.txt is in correct format. Please refer to http://circexplorer2.readthedocs.io/en/latest/tutorial/setup/.

**Comment by smm19900210** [comment]
thans  kepbod, how to convert gtf to refFlat.txt? i used gtfToGenePred, my command is ~/songmm/CIRCexplorer2-2.1.0/gtfToGenePred test.gtf Soly_refFlat.txt

**Comment by kepbod** [comment]
I think google is a good choice.

**Comment by smm19900210** [comment]
thanks!  kepbod
