### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by sambhav2mishra** [YangLab/CIRCexplorer2#34]
This is my command:

**tophat2 -o tophat_fusion -p 15 --fusion-search --keep-fasta-order --bowtie1 --no-coverage-search Bowtie1_index /userdata/Dramaresh/circtool_hela_cell/fastq_files/SRR5122011_1.fastq.gz /userdata/Dramaresh/circtool_hela_cell/fastq_files/SRR5122011_2.fastq.gz**

[2019-08-23 13:47:40] Beginning TopHat run (v2.0.12)
-----------------------------------------------
[2019-08-23 13:47:40] Checking for Bowtie
		  Bowtie version:	 1.2.3.0
[2019-08-23 13:47:40] Checking for Samtools
Traceback (most recent call last):
  File "/home/amaresh/tools/tophat-2.0.12.Linux_x86_64/tophat", line 4087, in <module>
    sys.exit(main())
  File "/home/amaresh/tools/tophat-2.0.12.Linux_x86_64/tophat", line 3885, in main
    check_samtools()
  File "/home/amaresh/tools/tophat-2.0.12.Linux_x86_64/tophat", line 1559, in check_samtools
    samtools_version_str, samtools_version_arr = get_samtools_version()
  File "/home/amaresh/tools/tophat-2.0.12.Linux_x86_64/tophat", line 1541, in get_samtools_version
    samtools_version_arr = [int(version_match.group(x)) for x in [1,2,3]]
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by kepbod** [comment]
Sorry, this error was from TopHat, so please post this issue to TopHat.
