### ISSUE TITLE
Not able to download mm10_ens.txt

### ISSUE THREAD

**Issue by sambhav2mishra** [YangLab/CIRCexplorer2#37]
fetch_ucsc.py mm10 ens mm10_ens.txt

Traceback (most recent call last):
  File "/usr/local/bin/fetch_ucsc.py", line 11, in <module>
    load_entry_point('CIRCexplorer2==2.3.7', 'console_scripts', 'fetch_ucsc.py')()
  File "build/bdist.linux-x86_64/egg/circ2/fetch_ucsc.py", line 86, in main
    
  File "build/bdist.linux-x86_64/egg/circ2/fetch_ucsc.py", line 52, in fetch_file
    
  File "/usr/lib/python2.7/gzip.py", line 463, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 267, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 302, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 196, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

**Comment by kepbod** [comment]
Thanks for the bug report. In UCSC, they have removed the ensembl gene annotations for mm10. Please use other gene annotations if you use fetch_ucsc.py to download gene annotations.
