### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by lliaokc** [YangLab/CIRCexplorer2#39]
Hi, 

I am running CIRCexplorer2 with the following commands [use CIRCexplorer2 parse to obtain back_spliced_junction.bed from STAR generated Chimeric.out.junction] :

CIRCexplorer2 annotate -r genome.gtf -g genome.fasta -b back_spliced_junction.bed -o outfiles

Then, I have the following error messages:

Start to annotate fusion junctions...
Traceback (most recent call last):
  File "/usr/local/bin/CIRCexplorer2", line 9, in <module>
    load_entry_point('CIRCexplorer2==2.3.8', 'console_scripts', 'CIRCexplorer2')()
  File "build/bdist.linux-x86_64/egg/circ2/command_parse.py", line 51, in main
  File "build/bdist.linux-x86_64/egg/circ2/helper.py", line 38, in wrapper
  File "build/bdist.linux-x86_64/egg/circ2/annotate.py", line 38, in annotate
    return attrs[key]
  File "build/bdist.linux-x86_64/egg/circ2/annotate.py", line 50, in annotate_fusion
    return get_name
  File "build/bdist.linux-x86_64/egg/circ2/parser.py", line 76, in parse_ref
ValueError: need more than 2 values to unpack

Could you please provide any suggestions to solve this problem? Thanks.

**Comment by kepbod** [comment]
`CIRCexplorer2 annotate` did not accept the gtf file. Please use the correct format for gene annotation file (https://circexplorer2.readthedocs.io/en/latest/modules/annotate/).
