### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JianGuoZhou3** [YangLab/CIRCexplorer2#44]
(cir2) [rstudio@Zhou-EU-2 CircRNA]$ CIRCexplorer2 annotate \
> -r ~/hdd/code/CircRNA/CIRC/hg38.v27.txt \
> -g ~/hdd/reference/hg38_ek12/GRCh38.primary_assembly.genome.fa \
> -b ~/EU-2/EGA/EGAD00001003977/RNA/CircRNA/EGAR00001652884_back_spliced_junction.bed \
> -o EGAR00001652884_circularRNA_known.txt \
> > EGAR00001652884_CIRCexplorer2_annotate.log

Traceback (most recent call last):
  File "/home/rstudio/miniconda2/envs/cir2/bin/CIRCexplorer2", line 10, in <module>
    sys.exit(main())
  File "/home/rstudio/miniconda2/envs/cir2/lib/python2.7/site-packages/CIRCexplorer2-2.3.8-py2.7.egg/circ2/command_parse.py", line 51, in main
  File "/home/rstudio/miniconda2/envs/cir2/lib/python2.7/site-packages/CIRCexplorer2-2.3.8-py2.7.egg/circ2/helper.py", line 38, in wrapper
  File "/home/rstudio/miniconda2/envs/cir2/lib/python2.7/site-packages/CIRCexplorer2-2.3.8-py2.7.egg/circ2/annotate.py", line 38, in annotate
    if key in attrs:
  File "/home/rstudio/miniconda2/envs/cir2/lib/python2.7/site-packages/CIRCexplorer2-2.3.8-py2.7.egg/circ2/annotate.py", line 50, in annotate_fusion

  File "/home/rstudio/miniconda2/envs/cir2/lib/python2.7/site-packages/CIRCexplorer2-2.3.8-py2.7.egg/circ2/parser.py", line 79, in parse_ref
IndexError: list index out of range
(cir2) [rstudio@Zhou-EU-2 CircRNA]$

**Comment by ericbrzoska** [comment]
Did you found a solution? I stuck on it, because I had to create a reference file for ensemble hg38 out of a gtf

**Comment by JianGuoZhou3** [comment]
> Did you found a solution? I stuck on it, because I had to create a reference file for ensemble hg38 out of a gtf

Hi @ericbrzoska  I successes using CIRCexplorer2.

````
CIRCexplorer2 annotate \
    -r ~/t12b/reference/hg38_ek12/hg38_ref_all.txt \
    -g ~/t12b/reference/hg38_ek12/GRCh38.primary_assembly.genome.fa \
    -b ${dir}/CircRNA/parse/${i}_back_spliced_junction.bed \
    -o ${i}_circularRNA_known.txt
````

**Comment by ericbrzoska** [comment]
First.. thanks you a lot for replying this fast..

I'm also using it, but I am working with a hg38 Assemby and a gtf from ensemble, so the fetch_ucsc algorithm hadn't the right reference file. I don't know how much it affects the algorithm when the Gtf I used in Tophat fusion doesn't fit to the reference File, so I found a way to convert a gtf to a refFlat-File. It also looks the same, but it throws the same Error... something about the Variable end

**Comment by JianGuoZhou3** [comment]
I also used gencode.
````
# --genomeFastaFiles ~/t12b/reference/hg38_ek12/GRCh38.primary_assembly.genome.fa \
# --sjdbGTFfile ~/t12b/reference/hg38_ek12/gencode.v34.annotation.gtf \
````

**Comment by ericbrzoska** [comment]
Okay, thank you!
