### ISSUE TITLE
ValueError while running align

### ISSUE THREAD

**Issue by KasperThystrup** [YangLab/CIRCexplorer2#48]
Hi
I'm trying to set up an experimental run by following the guide posted at readthedocs.io, yet I get a valueerror when I execute the `CIRCexplorer2 align` with my bowtie2 index files:

```
python ~/miniconda3/pkgs/circexplorer2-2.3.8-pyh864c0ab_1/site-packages/circ2/align.py -G hg19_kg.gtf -j bowtie2_index -f RNA_seq.fastq > CIRCexplorer2_align.log

Traceback (most recent call last):
  File "home/ME/miniconda3/pkgs/circexplorer2-2.3.8-pyh864c0ab_1/site-packages/circ2/align.py", line 29, in <module>
    from .parse import tophat_fusion_parse
ValueError: Attempted relative import in non-package
```

I have set up the following Conda environment
```
# packages in environment at /home/ME/miniconda3/envs/circexplorer2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                1.4.0                      py_0  
bedtools                  2.29.2               hc088bd4_0    bioconda
blas                      1.0                         mkl  
bowtie2                   2.2.5            py27h6bb024c_5    bioconda
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.7.22                     0  
certifi                   2019.11.28               py27_0  
cffi                      1.14.0           py27he30daa8_1  
chardet                   3.0.4                 py27_1003  
circexplorer2             2.3.8              pyh864c0ab_1    bioconda
cryptography              2.3.1            py27hc365091_0  
cufflinks                 2.2.1                    py27_2    bioconda
docopt                    0.6.2                    py27_0    anaconda
enum34                    1.1.6                    py27_1  
idna                      2.10                       py_0  
intel-openmp              2020.2                      254  
ipaddress                 1.0.23                     py_0  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2  
mkl                       2020.2                      256  
mkl-service               2.3.0            py27he904b0f_0  
mkl_fft                   1.0.15           py27ha843d7b_0  
mkl_random                1.1.0            py27hd6b4f25_0  
mysql-connector-c         6.1.11               hf4847fb_0  
ncurses                   6.2                  he6710b0_1  
numpy                     1.16.6           py27hbc911f0_0  
numpy-base                1.16.6           py27hde5b4d6_0  
openssl                   1.0.2u               h7b6447c_0  
pandas                    0.24.2           py27he6710b0_0  
perl                      5.26.2               h14c3975_0  
pip                       19.3.1                   py27_0  
pybedtools                0.8.1            py27he513fc3_0    bioconda
pycparser                 2.20                       py_2  
pyopenssl                 19.0.0                   py27_0  
pysam                     0.8.4                    py27_0    bioconda
pysocks                   1.7.1                    py27_0  
python                    2.7.18               h15b4118_1  
python-dateutil           2.8.1                      py_0  
pytz                      2020.1                     py_0  
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                     py_0  
scipy                     1.1.0            py27hfa4b5c9_1    anaconda
setuptools                44.0.0                   py27_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tophat                    2.1.1                    py27_3    bioconda
ucsc-bedgraphtobigwig     357                           1    bioconda
ucsc-bedtobigbed          357                           1    bioconda
ucsc-genepredtogtf        366                  h5eb252a_0    bioconda
ucsc-gtftogenepred        366                  h5eb252a_0    bioconda
urllib3                   1.25.7                   py27_0  
wheel                     0.35.1                     py_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  

```

Thank you for your time and help!

**Comment by KasperThystrup** [comment]
I can likewise add that I get an error at the same position when executing with system `python3.5` inside the above listed environment. However, I'm not certain whether all dependencies are installed correctly for this version.

```
Traceback (most recent call last):
  File "/home/kasper/miniconda3/pkgs/circexplorer2-2.3.8-pyh864c0ab_1/site-packages/circ2/align.py", line 29, in <module>
    from .parse import tophat_fusion_parse
SystemError: Parent module '' not loaded, cannot perform relative import

```

**Comment by kepbod** [comment]
Can you try to reinstall CIRCexplorer from scratch to check whether this error still occurs?
