### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by kopardev** [YangLab/CIRCexplorer2#51]
Here is the Traceback of my error:
```
Traceback (most recent call last):
  File "/opt/conda/bin/CIRCexplorer2", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python2.7/site-packages/circ2/command_parse.py", line 47, in main
    command=command_log, name='parse')
  File "/opt/conda/lib/python2.7/site-packages/circ2/helper.py", line 38, in wrapper
    fn(*args)
  File "/opt/conda/lib/python2.7/site-packages/circ2/parse.py", line 49, in parse
    options['-f'])
  File "/opt/conda/lib/python2.7/site-packages/circ2/parse.py", line 71, in tophat_fusion_parse
    for i, read in enumerate(parse_fusion_bam(fusion, pair_flag)):
  File "/opt/conda/lib/python2.7/site-packages/circ2/parser.py", line 44, in parse_fusion_bam
    chr1, chr2 = read.get_tag('XF').split()[1].split('-')
ValueError: too many values to unpack
Traceback (most recent call last):
  File "/opt/conda/bin/clear_quant", line 11, in <module>
    load_entry_point('CLEAR==1.0.1', 'console_scripts', 'clear_quant')()
  File "/opt/conda/lib/python2.7/site-packages/CLEAR-1.0.1-py2.7.egg/src/run.py", line 269, in main
    args.genome, args.gtf, circ_dir)
  File "/opt/conda/lib/python2.7/site-packages/CLEAR-1.0.1-py2.7.egg/src/run.py", line 195, in circ_annot
    subprocess.check_output(circ_parse)
  File "/opt/conda/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['CIRCexplorer2', 'parse', '-f', '-t', 'TopHat-Fusion', '/data/Ziegelbauer_lab/circRNADetection/ccbr983_v4/results/Rep6_KO_72h/CLEAR/fusion/accepted_hits.bam', '-b', '/data/Ziegelb
auer_lab/circRNADetection/ccbr983_v4/results/Rep6_KO_72h/CLEAR/circ/bsj.bed']' returned non-zero exit status 1
```
This is actually generated by CLEAR, but it seems like a circExplorer2 error where -t `Tophat-fusion` is not able to parse the bam file correctly.

**Comment by kopardev** [comment]
I think the issue relates to hyphens in my reference sequences' ids. I have ERCC sequences in my reference and they all have a hyphen in their ids, eg. **ERCC-0002**. I am trying to replace the hyphen with underscore to get around this issue.
