### ISSUE TITLE
parse

### ISSUE THREAD

**Issue by tanasa** [YangLab/CIRCexplorer2#54]
Dear all, i am encountering the following error during the parse phase . Would you please help ? Thanks a lot !

```
CIRCexplorer2 parse -t STAR Chimeric.out.junction > CIRCexplorer2_parse.log
Traceback (most recent call last):
  File "/home/bogdan/miniconda3/bin/CIRCexplorer2", line 11, in <module>
    load_entry_point('CIRCexplorer2==2.4.0', 'console_scripts', 'CIRCexplorer2')()
  File "/home/bogdan/miniconda3/lib/python3.7/site-packages/CIRCexplorer2-2.4.0-py3.7.egg/circ2/command_parse.py", line 50, in main
    command=command_log, name='parse')
  File "/home/bogdan/miniconda3/lib/python3.7/site-packages/CIRCexplorer2-2.4.0-py3.7.egg/circ2/helper.py", line 40, in wrapper
    fn(*args)
  File "/home/bogdan/miniconda3/lib/python3.7/site-packages/CIRCexplorer2-2.4.0-py3.7.egg/circ2/parse.py", line 55, in parse
    star_parse(options['<fusion>'], out)
  File "/home/bogdan/miniconda3/lib/python3.7/site-packages/CIRCexplorer2-2.4.0-py3.7.egg/circ2/parse.py", line 125, in star_parse
    flag = int(line.split()[6])
ValueError: invalid literal for int() with base 10: '--outFileNamePrefix
```

**Comment by tanasa** [comment]
I have solved it by removing some non-canonical chromosomes in the Chimeric.out.junction file, and finally, we did get the file : 
circularRNA_known.txt. Would you please let me know if there is a way to visualize the cirRNA in a simple way ? Thanks a lot :)

**Comment by kepbod** [comment]
CIRCexplorer2 currently did not support the visualization of circRNAs.
