### ISSUE TITLE
KeyError: '--cuff'

### ISSUE THREAD

**Issue by shelkmike** [YangLab/CIRCexplorer2#65]
When running "fast_circ.py denovo" from the latest version of CIRCexplorer2, I encountered the following error:

```
Traceback (most recent call last):
  File "/mnt/lustre/shelkmike/Work/Tools/Anaconda/bin/fast_circ.py", line 8, in <module>
    sys.exit(main())
  File "/mnt/lustre/shelkmike/Work/Tools/Anaconda/lib/python3.9/site-packages/circ2/fast_circ.py", line 71, in main
    denovo_command(options, work_dir, command_log)
  File "/mnt/lustre/shelkmike/Work/Tools/Anaconda/lib/python3.9/site-packages/circ2/fast_circ.py", line 114, in denovo_command
    denovo(options, command=command_log, name='denovo')
  File "/mnt/lustre/shelkmike/Work/Tools/Anaconda/lib/python3.9/site-packages/circ2/helper.py", line 38, in wrapper
    fn(*args)
  File "/mnt/lustre/shelkmike/Work/Tools/Anaconda/lib/python3.9/site-packages/circ2/denovo.py", line 54, in denovo
    cufflinks_ref_path = '%s/transcripts_ref.txt' % options['--cuff']
KeyError: '--cuff'
```

**Comment by z-bluesky** [comment]
I encountered the same problem too, and I think mybe fast_circ.py import donovo.py without the option of '--cuff'. But I konw little about python to edit the .py file, sorry

**Comment by shelkmike** [comment]
@bakillersky 
I've found a solution for this problem. After "fast_circ.py denovo" stops with this error, I run "CIRCexplorer2 denovo" separately with a command like this:
`CIRCexplorer2 denovo --ref=$path_to_the_file_with_information_on_genes --genome=$path_to_the_reference --bed=./CIRCexplorer2_results/back_spliced_junction.bed --cuff=./CIRCexplorer2_results/assemble/ --tophat=./CIRCexplorer2_results/alignment/tophat --output=./CIRCexplorer2_results/denovo/`

Here, "CIRCexplorer2_results" is the folder where "fast_circ.py denovo" wrote its results to.

**Comment by z-bluesky** [comment]
@shelkmike 
You are such a genius!!! thank you so much
